myapp/urls.py
from django.urls import path
from myapp import views

urlpatterns = [
    path('', views.home, name='home'),
    path('add-property/', views.add_property, name='addpost'),
    path('about/', views.about, name='about'),
    path('tutorial/', views.tutorial, name='tutorial'),
    path('sublet/', views.sublet, name='sublet'),
    path('settings/', views.settings, name='settings'),
    path('family/', views.family, name='family'),
    path('payment/', views.payment, name='payment'),
    path('bachelor/', views.bachelor, name='bachelor'),
    path('office/', views.office, name='office'),
    path('services/', views.services, name='services'),
    path('saveproperty/', views.saveproperty, name='saveproperty'),
    path('wishlist/<int:pk>/', views.wishlist, name='wishlist'),
    path('contact/', views.contact, name='contact'),
    path('property-single/', views.property_single, name='property-single'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('terms-and-conditions/', views.terms_and_conditions, name='terms_and_conditions'),
    path('faqs/', views.faqs, name='faqs'),
    path('Emergency/', views.Emergency, name='Emergency'),

]

tolet/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path('',include('users.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views


# create urls here
urlpatterns = [
    path('register/', views.signup, name='register'),
    path('login/', views.signin, name='login'),
    path('logout/', views.log_out, name='log_out'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.changePassword, name='change-password'),
    path('profile/', views.profile, name='profile'),
    
    # path('password-reset/', views.password_reset, name='password-reset'),
    # path('password-reset-done/', views.password_reset_done, name='password-reset-done'),
    # path('password-reset-confirm/', views.password_reset_confirm, name='password-reset-confirm'),



    # reset password url
    path('password-reset/', views.password_reset, name='password_reset'),
    path('password-reset-done/', views.password_reset_done,
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         views.password_reset_confirm, name='password_reset_confirm'),
    path('password-reset-complete/', views.password_reset_complete,
         name='password_reset_complete'),


     path('get_districts/<int:division_id>/', views.get_districts, name='get_districts'),
     path('get_upazilas/<int:district_id>/', views.get_upazilas, name='get_upazilas'),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from ckeditor.fields import RichTextField


# Create your models here.
class Service(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    icon = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


# Add Property
class Add_property(models.Model):
    propertytype = models.CharField(max_length=100)
    division = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    areaname = models.CharField(max_length=100)
    images = models.ImageField(upload_to='addproperty')


# class Add_property(models.Model):

#     # property Information
#     status = models.CharField(max_length=100)
#     propertytype = models.CharField(max_length=100)
#     size = models.CharField(max_length=100)
#     bedroom = models.CharField(max_length=100)
#     drawingroom = models.CharField(max_length=100)
#     diningroom = models.CharField(max_length=100)
#     balcony = models.CharField(max_length=100)
#     washroom = models.CharField(max_length=100)
#     rules = models.CharField(max_length=100)
#     comment = models.CharField(max_length=100)

#     # Add Location
#     division = models.CharField(max_length=100)
#     district = models.CharField(max_length=100)
#     areaname = models.CharField(max_length=100)

#     # Facilities
#     lift = models.BooleanField()
#     gas = models.BooleanField()
#     garage = models.BooleanField()
#     cc_camera = models.BooleanField()
#     security_guard = models.BooleanField()
#     swiming_pool = models.BooleanField()
#     store_room = models.BooleanField()
#     fire_extinguisher = models.BooleanField()

#     # Add Images
#     images = models.ImageField(upload_to='add_property')

#     # Owner Information
#     owner_name = models.CharField(max_length=100)
#     contact_number = models.IntegerField()
#     whatsapp_number = models.IntegerField()


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    message = models.TextField()
    contacted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class PrivacyPolicy(models.Model):
    title = models.CharField(max_length=200)
    content = RichTextField()
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Privacy Policy"
        verbose_name_plural = "Privacy Policy"


class TermsAndConditions(models.Model):
    title = models.CharField(max_length=200)
    content = RichTextField()
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Terms And Condition"
        verbose_name_plural = "Terms And Conditions"


class FAQ(models.Model):
    question = models.CharField(max_length=255)
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question

users/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from PIL import Image


# Create your models here.
class Division(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    def get_districts_url(self):
        return reverse('get_districts', args=[str(self.id)])


class District(models.Model):
    name = models.CharField(max_length=255)
    division = models.ForeignKey(Division, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.division}"

    def get_upazilas_url(self):
        return reverse('get_upazilas', args=[str(self.id)])


class Upazila(models.Model):
    name = models.CharField(max_length=255)
    district = models.ForeignKey(District, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.district}"


#username, email, first_name, last_name, groups, user_permissions
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15)
    profile_picture = models.ImageField(default='no-image.png', upload_to='profile')
    division = models.ForeignKey(Division, on_delete=models.SET_NULL, null=True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)
    upazila = models.ForeignKey(Upazila, on_delete=models.SET_NULL, null=True)
    area = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        # save the profile first
        super().save(*args, **kwargs)

        # resize the image
        img = Image.open(self.profile_picture.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            # create a thumbnail
            img.thumbnail(output_size)
            # overwrite the larger image
            img.save(self.profile_picture.path)

users/views.py
from django.shortcuts import render, redirect
from users.forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth import get_user_model
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.mixins import UserPassesTestMixin

from django.utils.encoding import force_bytes
from django.utils.encoding import force_str
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse
from tolet.settings import DEFAULT_FROM_EMAIL
from django.http import JsonResponse
from .models import *
UserModel = get_user_model()
from django.shortcuts import get_object_or_404


# Create your views here.
def get_districts(request, division_id):
    division = Division.objects.get(id=division_id)
    districts = District.objects.filter(division=division)
    data = [{'id': district.id, 'name': district.name} for district in districts]
    return JsonResponse(data, safe=False)

def get_upazilas(request, district_id):
    district = District.objects.get(id=district_id)
    upazilas = Upazila.objects.filter(district=district)
    data = [{'id': upazila.id, 'name': upazila.name} for upazila in upazilas]
    return JsonResponse(data, safe=False)


@login_required(login_url='login')
def dashboard(request):
    if not request.user.is_superuser:
        sms = 'Page Not Found'
        return render(request, 'messages.html', {'sms': sms}) 
    else:
        return render(request, 'dashboard.html')


def signin(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = LoginForm(request=request, data=request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                upass = form.cleaned_data['password']
                user = authenticate(username=uname, password=upass)
                if user is not None:
                    login(request, user)
                    messages.success(request, 'Logged in Successfully !!')
                    return redirect('dashboard')
                else:
                    # User authentication failed, so display an error message
                    messages.error(request, 'Invalid username or password')
            # If form is not valid, it will be re-rendered with form errors

        else:
            form = LoginForm()
        return render(request, 'login.html', {'form': form})
    else:
        return redirect('dashboard')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()

            # Log in the user
            login(request, user)

            # Provide user feedback
            messages.success(
                request, 'You have successfully registered and logged in.')

            # Redirect to a dashboard or profile page
            # Change 'dashboard' to the name of your dashboard URL
            if not request.user.is_superuser:
                return render(request, "user_profile.html")
            else:
                return render(request, "dashboard.html")

        else:
            # Display form errors
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f'{field.capitalize()}: {error}')

    else:
        form = SignUpForm()

    return render(request, 'register.html', {'form': form})


@login_required(login_url='login')
def log_out(request):
    logout(request)
    return redirect('home')


def changePassword(request):
    if request.method == 'POST':
        form = ChangePasswordForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
        return redirect('/')
    else:
        form = ChangePasswordForm(user=request.user)
    return render(request, 'change_password.html', {'form': form})




def password_reset(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = UserModel.objects.get(email=email)
        except UserModel.DoesNotExist:
            user = None

        if user:
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            token = default_token_generator.make_token(user)
            reset_link = reverse('password_reset_confirm', args=(uid, token))
            current_site = get_current_site(request)
            mail_subject = 'Password Reset Request'
            message = render_to_string('reset_email.html', {
                'user': user,
                'domain': current_site.domain,
                'reset_link': reset_link,
            })

            send_mail(mail_subject, message, DEFAULT_FROM_EMAIL, [email])
        return render(request, 'password_reset_done.html', {'email': email})
    return render(request, 'password_reset_form.html')


def password_reset_confirm(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = UserModel.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, UserModel.DoesNotExist):
        user = None

    if user and default_token_generator.check_token(user, token):
        if request.method == 'POST':
            new_password = request.POST.get('new_password')
            user.set_password(new_password)
            user.save()
            return redirect('password_reset_complete')
        return render(request, 'password_reset_confirm_form.html')
    else:
        return HttpResponse('Password reset link is invalid')


def password_reset_done(request):
    return render(request, 'password_reset_done.html')


def password_reset_complete(request):
    return render(request, 'password_reset_complete.html')



@login_required(login_url='login')
def profile(request):
    # Assuming you have a one-to-one relationship between User and Profile models
    
    try:
        profile = request.user.profile
    except Profile.DoesNotExist:
        # If the profile does not exist, create it
        profile = Profile.objects.create(user=request.user)
        
    
    if not request.user.is_superuser:
        return render(request, "user_profile.html", {'profile': profile})
    else:
        return render(request, "admin_profile.html", {'profile': profile})


@login_required(login_url='login')
def edit_profile(request):
    # Fetch all divisions, districts, and upazilas from the database
    divisions = Division.objects.all()
    districts = District.objects.all()
    upazilas = Upazila.objects.all()

    # Get the current user's profile
    profile = request.user.profile

    if request.method == 'POST':
        # Update User model fields
        request.user.first_name = request.POST.get('first_name', '')
        request.user.last_name = request.POST.get('last_name', '')
        request.user.email = request.POST.get('email', '')
        request.user.save()

        # Update Profile model fields
        profile.phone = request.POST.get('phone', '')

        # Fetch the Division instance based on the provided ID (assuming 'division' is the ID)
        division_id = request.POST.get('division', '')
        division = get_object_or_404(Division, id=division_id)
        profile.division = division

        # Fetch the District instance based on the provided ID (assuming 'district' is the ID)
        district_id = request.POST.get('district', '')
        district = get_object_or_404(District, id=district_id)
        profile.district = district

        # Fetch the Upazila instance based on the provided ID (assuming 'upazila' is the ID)
        upazila_id = request.POST.get('upazila', '')
        upazila = get_object_or_404(Upazila, id=upazila_id)
        profile.upazila = upazila

        if 'profile_picture' in request.FILES:
            profile.profile_picture = request.FILES.get('profile_picture')
            profile.save()


        profile.area = request.POST.get('area', '')
        profile.save()

        messages.success(request, 'Profile updated successfully.')
        return redirect('profile')  # Redirect to the profile page after saving changes

    # Render the edit profile form with initial data
    context = {
        'divisions': divisions,
        'districts': districts,
        'upazilas': upazilas,
        'profile': profile,  # Include the user's profile in the context
    }

    if not request.user.is_superuser:
        return render(request, "editProfile.html", context)
    else:
        return render(request, 'admin_edit_profile.html', context)

users/templates/admin_edit_profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}ToLet & Security | Admin-Edit-Profile{% endblock title %}

{% block content %}

<section id="dashboard-top">
    <div class="container">
        <div class="row justify-content-center">
            <!-- section 1 -->
            <div class="col-12 col-md-3 col-lg-3 mb-4">
                <div class="pt-5">
                    <img src="{% static 'images/profile_pic.png' %}" alt="Bariwala" class="img-fluid d-block  rounded-circle shadow"
                    style="width: 150px; height: 150px;">
                    <small class="px-5 text-muted" >@{{ request.user.username }}</small>
                
                    <ul class="nav flex-column mt-4">
                        <li class="nav-item mb-2">
                            <a class="nav-link active rounded-3 border" aria-current="page" href="/profile/">Profile Verification</a>
                        </li>
                        <li class="nav-item mb-2">
                            <a class="nav-link rounded-3 border" href="/change-password/">Change Password</a>
                        </li>
                        <li class="nav-item mb-2">
                            <a class="nav-link rounded-3 border" href="/services/">Services</a>
                        </li>
                        <li class="nav-item mb-2">
                            <a class="nav-link rounded-3 border" href="/settings/">Settings</a>
                        </li>
                        <li class="nav-item mb-2">
                            <a class="nav-link rounded-3 border" href="/logout/">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- section 2 -->
            <div class="col-12 col-md-9 col-lg-9 py-3 mb-4 pt-5">
                <div class="card p-2  text-center mb-5">
                    <p>Add your payment method and Ensure a hassle-free experience by 
                        verifying your profile with complete and accurate information. 
                        If you encounter any problems or have questions,
                         feel free to contact us. We are here to help you. 
                         Contact Informetion : 01751379009 
                    </p>
                </div>
            <!-- section 2.1 -->
                <h5>Personal Details</h5>
                <form action="" method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <div class="form-outline mb-3">
                                <label class="form-label" for="id_username">Username</label>
                                <input type="text" id="id_username" placeholder="Enter your short username" class="form-control" required>
                                <div class="invalid-feedback">Please enter a username.</div>
                            </div>
                            <div class="form-outline mb-3">
                                <label class="form-label" for="id_firstName">First name</label>
                                <input type="text" id="id_firstName" name="first_name" placeholder="Enter your first name" class="form-control" required>
                                <div class="invalid-feedback">Please enter your first name.</div>
                            </div>
                            <div class="form-outline mb-3">
                                <label class="form-label" for="id_email">E-mail</label>
                                <input type="email" id="id_email" name="email" placeholder="Enter your valid email" class="form-control" required>
                                <div class="invalid-feedback">Please enter a valid email address.</div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="form-outline mb-3">
                                <label class="form-label" for="id_profilePicture">Profile Picture</label>
                                <input type="file" id="id_profilePicture" name="profile_picture" class="form-control" required>
                                <div class="invalid-feedback">Please choose a profile picture.</div>
                            </div>
                            <div class="form-outline mb-3">
                                <label class="form-label" for="id_lastName">Last name</label>
                                <input type="text" id="id_lastName" name="last_name" placeholder="Enter your last name" class="form-control" required>
                                <div class="invalid-feedback">Please enter your last name.</div>
                            </div>
                            <div class="form-outline mb-3">
                                <label class="form-label" for="id_phoneNumber">Phone</label>
                                <input type="tel" id="id_phoneNumber" name="phone" placeholder="Enter your phone number" class="form-control" required>
                                <div class="invalid-feedback">Please enter a valid phone number.</div>
                            </div>
                        </div>
                    </div>
                    <h5 class="mt-2">Address</h5>
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <div class="form-outline mb-3">
                                <label class="form-label" for="id_division">Division</label>
                                <select name="division" id="id_division" class="form-select" required>
                                    <option value="" disabled selected>Choose a division</option>
                                    {% for division in divisions %}
                                        <option value="{{ division.id }}">{{ division.name }}</option>
                                    {% endfor %}
                                </select>
                                <div class="invalid-feedback">Please choose a division.</div>
                            </div>
                            <div class="form-outline mb-3">
                                <label class="form-label" for="id_district">District</label>
                                <select name="district" id="id_district" class="form-select" required>
                                    <option value="" disabled selected>Choose a district</option>
                                </select>
                                <div class="invalid-feedback">Please choose a district.</div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="form-outline mb-3">
                                <label class="form-label" for="id_upazila">Upazila</label>
                                <select name="upazila" id="id_upazila" class="form-select" required>
                                    <option value="" disabled selected>Choose an upazila</option>
                                </select>
                                <div class="invalid-feedback">Please choose an upazila.</div>
                            </div>
                            <div class="form-outline mb-3">
                                <label class="form-label" for="id_area">Area</label>
                                <input type="text" id="id_area" name="area" placeholder="Street / Zip Code / Block / Sector" class="form-control" required>
                                <div class="invalid-feedback">Please enter the area details.</div>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex gap-2 my-3 justify-content-end">
                        <a class="btn bg-secondary text-white" href="/profile/">Back</a>
                        <button class="btn btn-primary" type="submit">Save changes</button>
                    </div>
                </form>
                
            </div>
        </div>
    </div>
</section>
{% endblock content %}


{% block script %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function() {
        $('#id_division').change(function() {
            var divisionId = $(this).val();
            if (divisionId) {
                $('#id_district').prop('disabled', false);
                $.ajax({
                    url: `/get_districts/${divisionId}/`,
                    type: 'GET',
                    success: function(data) {
                        $('#id_district').empty();
                        $('#id_district').append('<option value="">---------</option>');
                        $.each(data, function(key, value) {
                            $('#id_district').append(`<option value="${value.id}">${value.name}</option>`);
                        });
                    }
                });
            } else {
                $('#id_district').prop('disabled', true);
                $('#id_upazila').prop('disabled', true);
                $('#id_district').empty();
                $('#id_upazila').empty();
                $('#id_district').append('<option value="">---------</option>');
                $('#id_upazila').append('<option value="">---------</option>');
            }
        });

        $('#id_district').change(function() {
            var districtId = $(this).val();
            if (districtId) {
                $('#id_upazila').prop('disabled', false);
                $.ajax({
                    url: `/get_upazilas/${districtId}/`,
                    type: 'GET',
                    success: function(data) {
                        $('#id_upazila').empty();
                        $('#id_upazila').append('<option value="">---------</option>');
                        $.each(data, function(key, value) {
                            $('#id_upazila').append(`<option value="${value.id}">${value.name}</option>`);
                        });
                    }
                });
            } else {
                $('#id_upazila').prop('disabled', true);
                $('#id_upazila').empty();
                $('#id_upazila').append('<option value="">---------</option>');
            }
        });
    });
</script>
{% endblock script %}

users/templates/change_password.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Login
{% endblock title %}


{% block content %}
<section id="change-password" class="my-5">
    <div class="container my-3">
        <div class="row justify-content-center">
            <div class="col-11 col-md-5 col-lg-5 shadow rounded p-4 bg-white">
                <h3 class="mb-5 text-center">Change your password</h3>
                <form action="" method="POST" novalidate>
                    {% csrf_token %}
                    {% for fm in form %}
                    <div class="form-group mb-3">
                        {{fm.label_tag}} {{fm}} <small class="text-danger"> {{fm.errors|striptags}} </small>
                    </div>
                    {% endfor %}

                    <div class="d-grid gap-2">
                        <input type="submit" class="btn btn-success" value="Change Password">
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

users/templates/messages.html
{% extends "base.html" %}
{% load static %}

{% block title %}ToLet & Security | Messages {% endblock title %}

{% block content %}
<style>
    .page_404{ padding:40px 0; background:#fff; font-family: 'Arvo', serif;
}

.page_404  img{ width:100%;}

.four_zero_four_bg{
 
 background-image: url(https://cdn.dribbble.com/users/285475/screenshots/2083086/dribbble_1.gif);
    height: 400px;
    background-position: center;
 }
 
 
 .four_zero_four_bg h1{
 font-size:80px;
 }
 
  .four_zero_four_bg h3{
       font-size:80px;
       }
       
       .link_404{      
  color: #fff!important;
    padding: 10px;
    background: #39ac31;
    margin: 20px ;
    display: inline-block;}
  .contant_box_404{ margin-top:-50px;}
</style>
<section class="page_404">
    <div class="container ">
        <div class="row">
            <div class="col-11 m-auto col-sm-offset-1 text-center justify-content-center align-content-center">
                <div class="four_zero_four_bg">
                    <h1 class="text-center ">404</h1>
                </div>
                <div class="contant_box_404">
                    <h3 class="h2">
                        {{sms}}
                    </h3>
                    <p>the page you are looking for not avaible!</p>
                    <a href="/" class="link_404">Go to Home</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

users/templates/password_reset_form.html
{% extends "base.html" %}



{% block content %}
<section id="password-reset-form" class="my-5">
    <div class="container my-3">
        <div class="row justify-content-center mt-5">
            <div class="col-11 col-md-8 col-lg-5 shadow rounded p-3">
                <h3 class="card-title text-center mb-4">Password Reset</h3>
                <form action="" method="post">
                    {% csrf_token %}

                    <!-- Email Input -->
                    <div class="mb-4">
                        <label for="id_email" class="form-label mb-2 fw-bold">E-mail address</label>
                        <input type="email" id="id_email" name="email" class="form-control" ="emailHelpBlock">
                        <div id="emailHelpBlock" class="form-text">
                            If the account exists, we'll email you instructions to reset the password.
                        </div>
                    </div>

                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-success">Reset Password</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}